apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataSciencePipelinesApplication
metadata:
  finalizers:
    - datasciencepipelinesapplications.opendatahub.io/finalizer
  name: dspa
  namespace: parasol-insurance
spec:
  apiServer:
    stripEOF: true
    dbConfigConMaxLifetimeSec: 120
    caBundleFileMountPath: ''
    caBundleFileName: ''
    applyTektonCustomResource: true
    deploy: true
    enableSamplePipeline: false
    autoUpdatePipelineDefaultVersion: true
    archiveLogs: false
    terminateStatus: Cancelled
    enableOauth: true
    trackArtifacts: true
    collectMetrics: true
    injectDefaultScript: true
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: pipelines
      host: minio-api-parasol-insurance.apps.cluster-mdwkc.mdwkc.sandbox2783.opentlc.com
      port: ''
      region: us-east-1
      s3CredentialsSecret:
        accessKey: minio_root_user
        secretKey: minio_root_password
        secretName: minio
      scheme: https
  persistenceAgent:
    deploy: true
    numWorkers: 2
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
